services:
  postgres:
    image: postgres:16-alpine
    container_name: task-management-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data

  backend:
    container_name: task-management-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    entrypoint:
      [
        "/backend/wait-for.sh",
        "${DB_HOST}:${DB_PORT}",
        "--",
        "/backend/start.sh",
      ]
    command: >
      sh -c 'migrate -path /backend/cmd/migration -database "postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?sslmode=disable" -verbose up && /backend/main'
volumes:
  db_volume:
