// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID          string      `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	CreatorID   int64       `json:"creator_id"`
	Deadline    time.Time   `json:"deadline"`
	Completed   bool        `json:"completed"`
	CreatedAt   time.Time   `json:"created_at"`
}

type User struct {
	ID             int64     `json:"id"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
}
