// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: task.sql

package store

import (
	"context"
	"time"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
  id,
  creator,
  name,
  deadline
) VALUES (
  $1, $2, $3, $4
) RETURNING id, name, creator, deadline, completed, created_at
`

type CreateTaskParams struct {
	ID       string    `json:"id"`
	Creator  string    `json:"creator"`
	Name     string    `json:"name"`
	Deadline time.Time `json:"deadline"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.Creator,
		arg.Name,
		arg.Deadline,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Creator,
		&i.Deadline,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}
