name: Backend workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test backend
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: task-management

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: $POSTGRES_DB
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.3/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate

      - name: Write environment variables to .env file
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: |
          echo "SERVER_PORT=8080" > .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=$POSTGRES_DB" >> .env
          echo "DB_USERNAME=$POSTGRES_USER" >> .env
          echo "DB_PASSWORD=$POSTGRES_PASSWORD" >> .env
          echo "DB_SCHEMA=public" >> .env
          echo "JWT_SECRET_KEY=$JWT_SECRET_KEY" >> .env
          echo "JWT_ACCESS_TOKEN_DURATION=720h" >> .env

      - name: Run migrations
        run: make migrate/up

      - name: Test
        run: make test
